name: adventuristlyfe
favicon: null
layout_spectrum: 0.39321
typography_spectrum: 0.3935379737522453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.28148022829554975
  lightness: 0.17251149262301624
  saturation: 0.2634524723980576
  rhythmicContrast: 0.9246321725659072
purpose: []
